name: capaci
description: "Capaci: 焦る妊活から、賢く待つ妊活へ。精子の時間を知るアプリ。"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0' # SDKバージョンはv3のままで問題ありません

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # P0/P1: グラフ表示 (v21系がv26系に変わっていますが、v31でも問題ないはずです)
  syncfusion_flutter_charts: ^26.1.42 # 以前の互換バージョンに戻します

  # *** 修正: Riverpod を v2 系にダウングレード ***
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # P2: 画像メモ
  image_picker: ^1.2.0

  # P1/P2: トースト (v8系に戻します)
  fluttertoast: ^8.2.6

  # 日付フォーマット用
  intl: ^0.19.0

  # --- V1.1 (5.1) データ永続化 ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # --- 追加機能パッケージ ---

  # P2: BBT入力
  numberpicker: ^2.1.2

  # P3: 初回コーチマーク (v3系に戻します)
  showcaseview: ^3.0.0

  # P3: エラーハンドリング
  logger: ^2.6.2

  # P3: カレンダー機能
  table_calendar: ^3.1.2

  # P3: カレンダー連携機能
  add_2_calendar: ^3.0.1

  # P3: プッシュ通知機能
  flutter_local_notifications: ^17.3.0 # v19でなくv17系

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # (v4系に戻します)
  flutter_lints: ^4.0.0

  # *** 修正: Riverpod / Hive / BuildRunner を v2 互換に統一 ***
  
  # riverpod_generator を v2 系にダウングレード
  riverpod_generator: ^2.4.0
  
  # build_runner を v2.4系にダウングレード
  build_runner: ^2.4.11
  
  # hive_generator (v2系)
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
